# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "workshed" do |workshed|
  end

  config.vm.hostname = "workshed"

  config.vm.box = "bento/centos-7.3"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "workshed"
     vb.cpus = "2"
     vb.memory = "1024"
  end

  config.disksize.size = "10GB"

  config.vm.provision "shell",
    privileged: false,
    path: "provision/bootstrap.sh"
end
